title: Appx Removal
actions:
  - !appx: {name: '*Microsoft.Windows.Ai.Copilot*', type: family}
  - !appx: {name: '*Microsoft.Copilot*', type: family}
  - !appx: {name: '*Microsoft.Microsoft3DViewer*', type: family}
  - !appx: {name: '*Microsoft.BingSearch*', type: family}
  - !appx: {name: '*Microsoft.WindowsCalculator*', type: family}
  - !appx: {name: '*Microsoft.WindowsCamera*', type: family}
  - !appx: {name: '*Clipchamp.Clipchamp*', type: family}
  - !appx: {name: '*Microsoft.WindowsAlarms*', type: family}
  - !appx: {name: '*Microsoft.549981C3F5F10*', type: family}
  - !appx: {name: '*Microsoft.Windows.DevHome*', type: family}
  - !appx: {name: '*MicrosoftCorporationII.MicrosoftFamily*', type: family}
  - !appx: {name: '*Microsoft.WindowsFeedbackHub*', type: family}
  - !appx: {name: '*Microsoft.GetHelp*', type: family}
  - !appx: {name: '*Microsoft.Getstarted*', type: family}
  - !appx: {name: '*microsoft.windowscommunicationsapps*', type: family}
  - !appx: {name: '*Microsoft.WindowsMaps*', type: family}
  - !appx: {name: '*Microsoft.MixedReality.Portal*', type: family}
  - !appx: {name: '*Microsoft.BingNews*', type: family}
  - !appx: {name: '*Microsoft.MicrosoftOfficeHub*', type: family}
  - !appx: {name: '*Microsoft.Office.OneNote*', type: family}
  - !appx: {name: '*Microsoft.Paint*', type: family}
  - !appx: {name: '*Microsoft.MSPaint*', type: family}
  - !appx: {name: '*Microsoft.People*', type: family}
  - !appx: {name: '*Microsoft.PowerAutomateDesktop*', type: family}
  - !appx: {name: '*MicrosoftCorporationII.QuickAssist*', type: family}
  - !appx: {name: '*Microsoft.SkypeApp*', type: family}
  - !appx: {name: '*Microsoft.ScreenSketch*', type: family}
  - !appx: {name: '*Microsoft.MicrosoftSolitaireCollection*', type: family}
  - !appx: {name: '*Microsoft.MicrosoftStickyNotes*', type: family}
  - !appx: {name: '*MicrosoftTeams*', type: family}
  - !appx: {name: '*MSTeams*', type: family}
  - !appx: {name: '*Microsoft.Wallet*', type: family}
  - !appx: {name: '*Microsoft.Todos*', type: family}
  - !appx: {name: '*Microsoft.WindowsSoundRecorder*', type: family}
  - !appx: {name: '*Microsoft.BingWeather*', type: family}
  - !appx: {name: '*Microsoft.WindowsTerminal*', type: family}
  - !appx: {name: '*Microsoft.Xbox*', type: family}
  - !appx: {name: '*Microsoft.GamingServices*', type: family}
  - !appx: {name: '*Microsoft.XboxGameCallableUI*', type: family}
  - !appx: {name: '*Microsoft.Xbox.TCUI*', type: family}
  - !appx: {name: '*Microsoft.XboxApp*', type: family}
  - !appx: {name: '*Microsoft.XboxGameOverlay*', type: family}
  - !appx: {name: '*Microsoft.XboxGamingOverlay*', type: family}
  - !appx: {name: '*Microsoft.XboxIdentityProvider*', type: family}
  - !appx: {name: '*Microsoft.XboxSpeechToTextOverlay*', type: family}
  - !appx: {name: '*Microsoft.GamingApp*', type: family}
  - !appx: {name: '*Microsoft.YourPhone*', type: family}
  - !appx: {name: '*Microsoft.ZuneMusic*', type: family}
  - !appx: {name: '*Microsoft.ZuneVideo*', type: family}

  - !appx: {name: '*WindowsBackup*', type: app}
  
  - !appx: {name: '*Client.CBS*', operation: clearCache}
  - !appx: {name: '*StartMenuExperienceHost*', operation: clearCache}
  - !appx: {name: '*Windows.Search*', operation: clearCache}

  # Outlook
  - !appx: {name: '*Microsoft.OutlookForWindows*', type: family}
  - !powerShell:
    command: |
      Get-AppxPackage *Microsoft.OutlookForWindows* | Remove-AppxPackage
    wait: true

  # Uninstall ONEDRIVE
  - !run: 
    exeDir: true
    wait: true
    exe: 'ONEDRIVE.cmd'

  # Uninstall Edge (credit ShadowWhisperer)
  - !run: 
    option: uninstall-edge 
    exeDir: true 
    wait: true 
    exe: 'EDGE.exe'
